import type {
  FetchResult,
  FetchedProduct,
  LightstoneAdapter,
  Product,
  ProductCode,
  PropertyRef,
  StructuredFields,
} from "./adapter";
import { PRODUCTS } from "./products";

// Stub adapter — returns clearly-marked SAMPLE data so the whole flow is
// demoable without live Lightstone credentials. Every document title is
// prefixed with "[SAMPLE]" so the Property Record can render a "not yet
// connected" banner, and every FetchedProduct carries source: "stub".

function sampleBody(product: Product, ref: PropertyRef): string {
  return [
    "════════════════════════════════════════════════════════════",
    " SAMPLE DATA — Lightstone is not yet connected to Dream OS.",
    "════════════════════════════════════════════════════════════",
    "",
    `Product      : ${product.label}`,
    `Code         : ${product.code}`,
    `Address      : ${ref.address ?? "(unknown)"}`,
    `Erf          : ${ref.erf ?? "(unknown)"}`,
    `Title Deed   : ${ref.deed ?? "(unknown)"}`,
    `Generated at : ${new Date().toISOString()}`,
    "",
    "This file is a placeholder generated by the stub Lightstone",
    "adapter. When Dream's Lightstone credentials are provisioned",
    "and the live adapter is switched on, this content becomes",
    "the actual Lightstone-issued document for the requested",
    "product.",
    "",
    "Adapter seam : lib/lightstone/live.ts (LiveLightstoneAdapter)",
    "Enable live  : set LIGHTSTONE_API_BASE + LIGHTSTONE_API_KEY",
    "",
  ].join("\n");
}

// Canned structured fields for the products that can plausibly return them.
// Values are obviously placeholder so no-one confuses them with real data.
function sampleStructured(code: ProductCode, ref: PropertyRef): StructuredFields | undefined {
  if (code === "title_deed" || code === "deeds_search") {
    return {
      title_deed_no: ref.deed ?? "T99999/2099",
      extent_sqm: 1234,
      owners: [
        { display_name: "SAMPLE OWNER (STUB DATA)", is_current: true },
      ],
    };
  }
  if (code === "ownership") {
    return {
      owners: [
        { display_name: "SAMPLE PRIOR OWNER (STUB)", is_current: false },
        { display_name: "SAMPLE CURRENT OWNER (STUB)", is_current: true },
      ],
    };
  }
  return undefined;
}

export class StubLightstoneAdapter implements LightstoneAdapter {
  listProducts(): Product[] {
    return PRODUCTS;
  }

  async fetchProducts(
    ref: PropertyRef,
    productCodes: ProductCode[],
  ): Promise<FetchResult> {
    const fetched: FetchedProduct[] = [];
    const errors: string[] = [];

    for (const code of productCodes) {
      const product = PRODUCTS.find((p) => p.code === code);
      if (!product) {
        errors.push(`unknown product code: ${code}`);
        continue;
      }

      const body = sampleBody(product, ref);
      const bytes = new TextEncoder().encode(body);
      const addressSlug = (ref.address ?? "unknown")
        .replace(/[^a-zA-Z0-9]+/g, "-")
        .slice(0, 60);
      const title = `[SAMPLE] Lightstone ${product.label} — ${addressSlug}`;

      fetched.push({
        code,
        label: product.label,
        source: "stub",
        documentTitle: title,
        documentBytes: bytes,
        documentMime: "text/plain",
        structuredFields: sampleStructured(code, ref),
      });
    }

    return { source: "stub", fetched, errors };
  }
}
