-- ============================================================================
-- Dream Knysna OS — 0001 init: extensions, enums, reference/lookup tables
-- ============================================================================
-- Conventions:
--   * property_id (and every other PK) is a UUID, generated by gen_random_uuid().
--   * ENUMs are for tiny, stable sets the app branches on (a new value = migration).
--   * LOOKUP tables are for sets that grow / that Bronwyn may edit without a deploy
--     (country, suburb, ownership_type, property_type, document_type, compliance_type).
--   * All timestamps are timestamptz, defaulted to now().
-- ============================================================================

create extension if not exists pgcrypto;      -- gen_random_uuid()
create extension if not exists postgis;        -- geography/geometry for the map + cadastre
create extension if not exists citext;         -- case-insensitive email/text

-- ---------------------------------------------------------------------------
-- Shared trigger: keep updated_at current
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Party / people ------------------------------------------------------------
create type party_type as enum (
  'individual', 'company', 'close_corporation', 'trust',
  'partnership', 'deceased_estate', 'other'
);

create type matrimonial_regime as enum (
  'single', 'married_in_community', 'married_anc_no_accrual',
  'married_anc_with_accrual', 'foreign_marriage', 'divorced', 'widowed', 'unknown'
);

create type tax_residency as enum ('resident', 'non_resident', 'unknown');

-- Access / users ------------------------------------------------------------
create type app_role as enum ('admin', 'agent', 'conveyancer', 'client');

-- Mandate / listing ---------------------------------------------------------
create type mandate_type as enum ('sole', 'joint', 'open', 'exclusive');
create type mandate_evidence as enum ('signed_pdf', 'email_thread', 'verbal_note');
create type listing_status as enum ('draft', 'live', 'under_offer', 'sold', 'withdrawn', 'expired');

-- Transfer (one ownership-change cycle) -------------------------------------
create type transfer_status as enum (
  'preparing', 'mandate', 'listed', 'under_offer', 'sale_agreed',
  'in_conveyancing', 'registered', 'cancelled', 'lapsed'
);

-- Offers --------------------------------------------------------------------
create type offer_status as enum (
  'draft', 'submitted', 'countered', 'accepted', 'rejected', 'withdrawn', 'lapsed'
);

-- Agreements (gap #2: versioning + execution state) -------------------------
create type agreement_type as enum (
  'sale_improved', 'sale_land_freehold', 'movables', 'lease', 'addendum'
);
create type agreement_status as enum (
  'template', 'draft', 'clean_final', 'executed', 'cancelled'
);

-- Suspensive conditions (gap: conditions with lifecycle) --------------------
create type suspensive_condition_type as enum (
  'bond_approval', 'sale_of_purchasers_property', 'due_diligence',
  'deposit_payment', 'guarantee_delivery', 'other'
);
create type condition_status as enum ('pending', 'fulfilled', 'waived', 'failed');

-- Milestones / obligations (gap: dated deadlines) ---------------------------
create type milestone_type as enum (
  'deposit_due', 'guarantee_due', 'bond_grant', 'transfer_date',
  'occupation_date', 'lodgement', 'registration', 'condition_deadline', 'other'
);
create type milestone_status as enum ('pending', 'met', 'overdue', 'not_applicable');

-- FICA ----------------------------------------------------------------------
create type fica_role as enum (
  'seller', 'purchaser', 'director', 'member', 'trustee', 'partner', 'ubo', 'agent'
);
create type fica_status as enum ('outstanding', 'received', 'verified', 'expired');
create type fica_risk as enum ('low', 'medium', 'high');

-- Documents (gap #2) --------------------------------------------------------
create type document_status as enum ('template', 'draft', 'final', 'executed', 'superseded');

-- Media / drawings (gap #3: plans are first-class, not just photos) ---------
create type media_kind as enum (
  'photo', 'aerial', 'floor_plan', 'elevation', 'section',
  'concept_plan', 'site_plan', 'other'
);

-- Communications (gap #4) ---------------------------------------------------
create type comm_channel as enum ('email', 'whatsapp', 'phone', 'sms', 'portal', 'note', 'meeting');
create type comm_direction as enum ('inbound', 'outbound', 'internal');

-- Commission ----------------------------------------------------------------
create type commission_status as enum ('pending', 'invoiced', 'paid', 'cancelled');

-- Estates / schemes ---------------------------------------------------------
create type estate_kind as enum ('estate', 'sectional_scheme', 'hoa', 'share_block');

-- ============================================================================
-- LOOKUP TABLES (editable reference data; FK targets)
-- ============================================================================

create table country (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,        -- ISO alpha-2 (ZA, GB, AU, MU)
  name        text not null,
  sort_order  int  not null default 100,
  active      boolean not null default true
);

create table suburb (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  town        text not null default 'Knysna',
  sort_order  int  not null default 100,
  active      boolean not null default true,
  unique (name, town)
);

create table ownership_type (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  label       text not null,
  active      boolean not null default true
);

create table property_type (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  label       text not null,
  active      boolean not null default true
);

create table document_type (
  id             uuid primary key default gen_random_uuid(),
  code           text not null unique,
  label          text not null,
  category       text not null,            -- listing | mandate | agreement | fica | compliance | plan | company | municipal | correspondence | other
  is_pii_default boolean not null default false,
  retention_years int,                     -- FIC Act = 5; null = no rule
  active         boolean not null default true
);

create table compliance_type (
  id              uuid primary key default gen_random_uuid(),
  code            text not null unique,
  label           text not null,
  validity_months int,                     -- e.g. electrical CoC guidance; null = n/a
  active          boolean not null default true
);
